services:
  mysql8:
    container_name: bank-demo
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: client123@
      MYSQL_DATABASE: banking_db
    volumes:
      - bank-data:/var/lib/mysql
volumes:
  bank-data: